// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreWebApiBoilerPlate.Data;

namespace NetCoreWebApiBoilerPlate.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210726190904_SeedInitialData")]
    partial class SeedInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetCoreWebApiBoilerPlate.Domain.Entities.ExampleMasterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MasterStatusEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MasterStatusEntityId");

                    b.ToTable("ExampleMasterEntity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("102b566b-ba1f-404c-b2df-e2cde39ade09"),
                            DOB = new DateTime(1988, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Carlos",
                            Gender = true,
                            LastName = "Vaquedano",
                            MasterStatusEntityId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96")
                        });
                });

            modelBuilder.Entity("NetCoreWebApiBoilerPlate.Domain.Entities.MasterDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExampleMasterEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExampleMasterEntityId");

                    b.ToTable("MasterDetailEntity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b3621c0-7b12-4e80-9c8b-3398cba7ee05"),
                            ExampleMasterEntityId = new Guid("102b566b-ba1f-404c-b2df-e2cde39ade09"),
                            Price = 1f,
                            Quantity = 10,
                            Total = 100f,
                            Value = "Detail Value"
                        });
                });

            modelBuilder.Entity("NetCoreWebApiBoilerPlate.Domain.Entities.MasterStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MasterStatusEntity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            Description = "An active entity",
                            Value = "Active"
                        },
                        new
                        {
                            Id = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            Description = "An Inactive entity",
                            Value = "Inactive"
                        });
                });

            modelBuilder.Entity("NetCoreWebApiBoilerPlate.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Email = "chvb2002@gmail.com",
                            FirstName = "Carlos",
                            LastName = "Vaquedano",
                            Password = "5f9537838499389e3819df87bf03fa035dc82c7b47123f84b89dd324812ea548",
                            Status = 1,
                            Username = "cvaquedano"
                        });
                });

            modelBuilder.Entity("NetCoreWebApiBoilerPlate.Domain.Entities.ExampleMasterEntity", b =>
                {
                    b.HasOne("NetCoreWebApiBoilerPlate.Domain.Entities.MasterStatusEntity", "MasterStatusEntity")
                        .WithMany()
                        .HasForeignKey("MasterStatusEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterStatusEntity");
                });

            modelBuilder.Entity("NetCoreWebApiBoilerPlate.Domain.Entities.MasterDetailEntity", b =>
                {
                    b.HasOne("NetCoreWebApiBoilerPlate.Domain.Entities.ExampleMasterEntity", "ExampleMasterEntity")
                        .WithMany("MasterDetailEntities")
                        .HasForeignKey("ExampleMasterEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExampleMasterEntity");
                });

            modelBuilder.Entity("NetCoreWebApiBoilerPlate.Domain.Entities.ExampleMasterEntity", b =>
                {
                    b.Navigation("MasterDetailEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
